# Generated by Django 6.0.5 on 2026-05-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/images/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
