# Generated by Django 6.0.5 on 2026-05-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_image_file_lesson_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(default=60),
        ),
    ]
